### ISSUE TITLE
cant use next or stop

### ISSUE THREAD

**Issue by luel87** [stevenleeg/geemusic#112]
if i use my echo to start an activity of my logitech account to turn on my ac, i couldnt get gee music to skip to the next music or stop. it always give me the response that logitech harmony is not in the mode or logitech is not responding.. pls help

**Comment by luel87** [comment]
Yes i tried that and its still the same. The only workaround for me is not to use the echo to start any logitech activity. Temporarily i am using my phone to turn on our ac and use echo solely for geemusic. I also want to thank you sir for creating geemusic. It helped me save lot of money after i cancel my other music subscription. That is a huge help especially from someone in the Philippines. Thank you so much Sir Stevenleeg

**Comment by stevenleeg** [comment]
Okay yeah, I have a feeling the issue is that the Alexa API is kicking us to the background and when you say "Alexa next" it's trying to forward that intent to the Logitech skill rather than Geemusic. I think a solution to this would be for us to create our own utterance so you can say things like "Alexa, tell Geemusic to skip", which would explicitly send the action to geemusic (and ideally move it to the foreground so that future skips wouldn't need to use the geemusic prefix).

@PostsDesert or @kuruoujou would either of you have the bandwidth to take something like this on? It should be as simple as redirecting some new utterances to the skip/pause/play intents. I actually don't have Google Music anymore (Spotify stole me away) so it's been hard for me to continue developing this on my own :'(.

Also @luel87 you are very welcome! It's amazing to hear that this project has brought some good to someone else's life 😄 .
