### ISSUE TITLE
Following the UK instructions only works if you remove a couple of utterances.

### ISSUE THREAD

**Issue by cooperaj** [stevenleeg/geemusic#132]
It appears they're not defined in the intents file for UK users.

Specifically:
GeeMusicPlaySimilarSongsRadioIntent
GeeMusicPlayArtistRadioIntent

I removed them and things are now working, but should I have added the intents to the intents file?

**Comment by pprotschka** [comment]
same issue here for german.

**Comment by gricey** [comment]
Confirmed UK here, had to do the same thing

**Comment by stevenleeg** [comment]
A PR is welcome if this ends up being a common solution to the issue! I'm `en_US` so it's a bit difficult for me to test.

**Comment by fergyfresh** [comment]
@digiltd is this still an issue? Your e-mail address was UK so I'm making a bold assumption that this is something you could help clear up.

**Comment by digiltd** [comment]
sorry, no idea

though i expect the issue was before the new skill dev portal changes

the intents are in the json https://github.com/stevenleeg/geemusic/blob/master/speech_assets/non_us_custom_slot_version/interactionModel.json 

i would close it and if the problem is still an issue someone can reopen the issue :)
