### ISSUE TITLE
Radios for artists not working (potentially in general)

### ISSUE THREAD

**Issue by TheModdersDen** [stevenleeg/geemusic#156]
Every artist I seem to get a radio to play for seems to result in the response: "Sorry, I couldn't find that artist". This even applies to when I try to get a radio station to play based off a specific song. I am using a free account. Is this the problem?

**Comment by TheModdersDen** [comment]
@stevenleeg Any comments? I'm both confused and sad that I can't get radios to work...

**Comment by fergyfresh** [comment]
I just looked at it and I think I can add some value to this discussion.
In `intentSchema.json` the json seems to pass the value of `artist_name` to our `flask-ask` app to the key `name`. 
```
39             "intent": "GeeMusicPlayArtistRadioIntent", 
40             "slots": [ 
41                 {"name":"artist_name", "type":"AMAZON.MusicGroup"} 
42             ] 
43         }, 
```

You can see that the `artist_name` comes in from Alexa as `artist_name` in the `sampleUtterances.txt`
```
25 GeeMusicPlayArtistRadioIntent Start radio for artist {artist_name} 
26 GeeMusicPlayArtistRadioIntent Create a radio station for artist {artist_name} 
27 GeeMusicPlayArtistRadioIntent Start {artist_name} artist radio 
28 GeeMusicPlayArtistRadioIntent Start artist radio for {artist_name} 
29 GeeMusicPlayArtistRadioIntent Play artists like {artist_name} 
```

So I think it's as easy as changing this in `selection.py`
```
179 @ask.intent("GeeMusicPlayArtistRadioIntent") 
180 def play_artist_radio(artist_name): 
181     # Fetch the artist 
182     artist = api.get_artist(artist_name) 
```

To
```
179 @ask.intent("GeeMusicPlayArtistRadioIntent") 
180 def play_artist_radio(name): 
181     # Fetch the artist 
182     artist = api.get_artist(name) 
```
The reason I'm saying this is because I think the `intentSchema.json` binds the words you say to Alexa to our Heroku server (or whatever server you're using). I can't try this as I won't be at a computer that I can test this on, but what do you guys think?

**Comment by fergyfresh** [comment]
#worksforme

Radios work for me. Must be a limitation of the free account. Can you do it from the website directly on the Official Google Play Music?

**Comment by fergyfresh** [comment]
Its weird sometimes the `Play Radio for Artist {{ artist }}`, but you can sometimes play a song by an artist and then make a radio from that. That's what I've gotten to work so far.

Basically:
`Start radio for artist {artist_name}` didn't work

But playing a song by `{{ artist_name}}` and then saying `Start radio with this song` worked to start a radio with that song by that artist. If that makes sense.
