### ISSUE TITLE
Please create more detail guide about SSL

### ISSUE THREAD

**Issue by romankot** [stevenleeg/geemusic#217]
Unfortunately, didn't manage to make it work with any approach

**Comment by fergyfresh** [comment]
not even the heroku approach or the new zappa-deploy PR?

**Comment by romankot** [comment]
Thanks. I'll try. How much will it cost? 
The idea to run geemusic on raspberry pi3.

**Comment by fergyfresh** [comment]
Free on heroku.


Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Roman Kot <notifications@github.com> Date: 5/21/18  5:19 AM  (GMT-05:00) To: stevenleeg/geemusic <geemusic@noreply.github.com> Cc: Billy Ferguson <william.d.ferg@gmail.com>, Comment <comment@noreply.github.com> Subject: Re: [stevenleeg/geemusic] Please create more detail guide about SSL (#217) 
Thanks. I'll try. How much will it cost?

The idea to run geemusic on raspberry pi3.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.
{"@context":"http://schema.org","@type":"EmailMessage","potentialAction":{"@type":"ViewAction","target":"https://github.com/stevenleeg/geemusic/issues/217#issuecomment-390600624","url":"https://github.com/stevenleeg/geemusic/issues/217#issuecomment-390600624","name":"View Issue"},"description":"View this Issue on GitHub","publisher":{"@type":"Organization","name":"GitHub","url":"https://github.com"}}
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/stevenleeg/geemusic","title":"stevenleeg/geemusic","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/stevenleeg/geemusic"}},"updates":{"snippets":[{"icon":"PERSON","message":"@romankot in #217: Thanks. I'll try. How much will it cost? \r\nThe idea to run geemusic on raspberry pi3. "}],"action":{"name":"View Issue","url":"https://github.com/stevenleeg/geemusic/issues/217#issuecomment-390600624"}}}
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "37567f93-e2a7-4e2a-ad37-a9160fc62647",
"title": "Re: [stevenleeg/geemusic] Please create more detail guide about SSL (#217)",
"sections": [
{
"text": "",
"activityTitle": "**Roman Kot**",
"activityImage": "https://avatars3.githubusercontent.com/u/1821783?s=160\u0026v=4",
"activitySubtitle": "@romankot",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"stevenleeg/geemusic\",\n\"issueId\": 217,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"stevenleeg/geemusic\",\n\"issueId\": 217\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/stevenleeg/geemusic/issues/217#issuecomment-390600624"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 337171272\n}"
}
],
"themeColor": "26292E"
}

**Comment by fergyfresh** [comment]
Also, setting up an SSL cert on your Raspberry PI is ENTIRELY out of scope of this project.

**Comment by stevenleeg** [comment]
Yeah, going to have to agree with ^. Closing this for now.
