### ISSUE TITLE
libssl-dev

### ISSUE THREAD

**Issue by rbowden91** [stevenleeg/geemusic#23]
On a fresh Ubuntu install, I think you will also need to do:

sudo apt-get install libssl-dev

In order for pip to successfully install the cryptography package (or at least, I had to).

**Comment by alexbaucom17** [comment]
I also needed libffi-dev in addition to libssl-dev. Might be worth a note in the readme

**Comment by PostsDesert** [comment]
These packages aren't included in `python-dev`?

**Comment by rbowden91** [comment]
Hmm libssl-dev seems to be under Precise (http://packages.ubuntu.com/precise/python-dev and then under the python2.7-dev dependency), but not under Xenial (http://packages.ubuntu.com/xenial/python-dev) as far as I can tell.

**Comment by alexbaucom17** [comment]
I was also on Raspbian (which is a port of Debian Jessie... i think?) so dependencies for me might have been a bit different. But I did install python-dev before starting and did have to manually install those other two packages because the installation was failing. Overall not a huge deal to someone who has a general idea of what is going on, but might be a bit more of a deterrent to someone without much experience and just trying to blindly follow the readme.

**Comment by PostsDesert** [comment]
Okay, yeah that would make sense.

**Comment by stevenleeg** [comment]
Sure, I'll drop a note into the README for those.

**Comment by stevenleeg** [comment]
Could someone check out #24 and give it a 👍 before I merge?
