### ISSUE TITLE
Google API Change?

### ISSUE THREAD

**Issue by edjbush** [stevenleeg/geemusic#237]
I've noticed that I no longer access (or play) anything on Google Music. I noticed that some of the issues are now labelled google-api-change. Should I assume Google has gone and changed the api and that this app no longer works? Thanks.

**Comment by fergyfresh** [comment]
No, I just went through and cleaned up a bunch of issues because there were a lot of duplicates issues and a bunch of fixed issues so i just went through and consolidated them. There are three main GPS API issues that we know of. Each of the threads labeled google-api-issue are pretty old issues that have existed for the better part of the year.

**Comment by fergyfresh** [comment]
One issue is that you basically need to use an APP Password and can't use your 'normal' google password. The second issue is that you need to get a DEVICE_ID for an android device if you wanna deploy this skill on any PAAS/IAAS like Heroku or AWS. The third one is that you can only have 10 devices registered to your Google Play Music account, so if you exceed that limit you have to personally go into your google play music app and de-register some devices to get under the limit.
