### ISSUE TITLE
"Error: Failed building the interaction model." when pasting into Skill at Amazon using English/UK

### ISSUE THREAD

**Issue by JonTheNiceGuy** [stevenleeg/geemusic#53]
I have copied and pasted the contents of speech_assets/intentSchema.json into the Intents field, and speech_assets/sampleUtterances.txt into the Sample Utterances field.

This returns an error message about being unable to build the interaction model (as per the title of the issue).

Changing to English/US, this builds successfully.

**Comment by digiltd** [comment]
This is because the UK/DE are being denied access to the same tools as the US. This skill uses the the new built-in library to identify the differences between a song title, artist name, album name etc 

I knocked up a workaround where you can use custom slots instead

https://gist.github.com/digiltd/afd67485edc5baef037c58e021ffa48f

Then create custom slot types for the following and fill them with lists of example content. You don't have to include your entire library, I use a sample selection of about 20 tracks and use the Album name for MUSICALBUM, Artist or Group for MUSICGROUP, track title for MUSICRECORDING.

MUSICALBUM
MUSICGROUP
MUSICPLAYLIST
MUSICRECORDING

This will build the Skill for you, though for me I am not having much luck getting it to play audio, I can see the intent going through with the correct artist when I request, but she always says that she can't find the song. Though I do think this is more to do with the subscriber/free differences.

**Comment by stevenleeg** [comment]
Looks like this is now a known issue in the README (see #52). I'm on a US device so it's hard for me to test this, but if someone else would like to submit a PR for documenting that workaround I'm happy to merge!
