### ISSUE TITLE
Last.FM scrobbling won't work

### ISSUE THREAD

**Issue by yurijmikhalevich** [stevenleeg/geemusic#85]
Attempt to setup Last.FM scrobbling results in error:

```12:03:34 web.1  | Traceback (most recent call last):
12:03:34 web.1  |   File "/home/geemusic/geemusic/.venv/lib/python3.5/site-packages/flask/app.py", line 1994, in __call__
  :03:34 web.1  |     return self.wsgi_app(environ, start_response)
12:03:34 web.1  |   File "/home/geemusic/geemusic/.venv/lib/python3.5/site-packages/flask/app.py", line 1985, in wsgi_app
12:03:34 web.1  |     response = self.handle_exception(e)
12:03:34 web.1  |   File "/home/geemusic/geemusic/.venv/lib/python3.5/site-packages/flask/app.py", line 1540, in handle_exception
12:03:34 web.1  |     reraise(exc_type, exc_value, tb)
12:03:34 web.1  |   File "/home/geemusic/geemusic/.venv/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
12:03:34 web.1  |     raise value
12:03:34 web.1  |   File "/home/geemusic/geemusic/.venv/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
12:03:34 web.1  |     response = self.full_dispatch_request()
12:03:34 web.1  |   File "/home/geemusic/geemusic/.venv/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
12:03:34 web.1  |     rv = self.handle_user_exception(e)
12:03:34 web.1  |   File "/home/geemusic/geemusic/.venv/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
12:03:34 web.1  |     reraise(exc_type, exc_value, tb)
12:03:34 web.1  |   File "/home/geemusic/geemusic/.venv/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
12:03:34 web.1  |     raise value
12:03:34 web.1  |   File "/home/geemusic/geemusic/.venv/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
12:03:34 web.1  |     rv = self.dispatch_request()
12:03:34 web.1  |   File "/home/geemusic/geemusic/.venv/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
12:03:34 web.1  |     return self.view_functions[rule.endpoint](**req.view_args)
12:03:34 web.1  |   File "/home/geemusic/geemusic/geemusic/controllers.py", line 12, in redirect_to_stream
12:03:34 web.1  |     from utils import last_fm
12:03:34 web.1  | ImportError: No module named 'utils'```

**Comment by huberf** [comment]
Scrobbling has consistently worked for me. I'm away from my computer until late this evening, but recommend you verify that you can import a module from a subdirectory in your Python installation. I'll do some tests once I'm able.

**Comment by 39dotyt** [comment]
@huberf

- in the published `geemusic/controllers.py` last_fm import should be done like `from .utils import last_fm` (with dot in front of utils);
- published `geemusic/utils/last_fm.py` is not compatible with python3: `sorted(dict.keys())` shall be used instead of `dict.keys().sort()` and `md5` module should be replaced with `hashlib`;
- documentation is mentioning incorrect key `LAST_FM_SECRET`, it will work with `LAST_FM_API_SECRET`.

Are you using the same version as published?

I managed to make it work after implementing the changes I'm talking about above. But the playback is being interrupted in the beginning of the second song (not sure whether it related to scrobbling feature or not). Also scrobbling feature is working time-wise inaccurate. It will scrobble tracks and the beginning of playback, sometimes scrobble two tracks at a time (including the next track) and doesn't report "currently playing" state.

**Comment by 39dotyt** [comment]
> Also scrobbling feature is working time-wise inaccurate, sometimes scrobble two tracks at a time (including the next track).

It always scrobble one track ahead.

**Comment by huberf** [comment]
The source definitely stems from the Last.fm integration being built for Python 2.7. I'm still using the GeeMusic version for Python 2.7, so this is assuredly the issue. I'll update the code to Python 3 when I find the time unless you are able to do so earlier.
With the version I'm running, playback isn't interrupted, and I've successfully scrobbled all songs from an artist when instructing GeeMusic to play songs from one. However, as I haven't tested the latest GeeMusic version, I can't be certain if updates to the code have caused the Last.fm integration to interfere.
Because it didn't appear that Alexa kept a persistent connection with the GeeMusic server after grabbing the streaming URL, the scrobble function immediately executes and saves the song Alexa just grabbed, disregarding the 50%+ completion Last.fm recommends. Unless the GeeMusic server can somehow determine the current song completion, I don't see a proper way around this. If one created a persistent scrobble queue, and only scrobbled the played song if a GeeMusic didn't receive a new streaming URL request before the song duration/2 had passed. However, this wouldn't solve the use case where a user has requested only a single song, and there wouldn't be a way to tell if they had completed the song, paused it, or stopped it early.

**Comment by huberf** [comment]
@yurijmikhalevich FYI, I fixed the Last.fm integration to work with Python 3.x. It is a merged PR, so if you have the latest version of the repo, it should be included. For reference, my PR is at https://github.com/stevenleeg/geemusic/pull/127

**Comment by stevenleeg** [comment]
This hasn't seen any recent activity and will therefore be closed. Feel free to comment or file a new issue if you're still having trouble.
