### ISSUE TITLE
Streaming does not work with Foreman/ngrok

### ISSUE THREAD

**Issue by quantumf** [stevenleeg/geemusic#93]
I'm trying to follow the instructions precisely as per the readme. I've set up foreman and ngrok. Everything seems to be fine, but nothing streams to the echo. 

My .env:

```bash
GOOGLE_EMAIL=chris.welsh@gmail.com
GOOGLE_PASSWORD=<pw>

APP_URL=https://<ngrok-code>.ngrok.io
```

My Foreman output:

```bash
19:17:59 web.1  | 127.0.0.1 - - [01/May/2017 19:17:59] "POST /alexa HTTP/1.1" 200 -
19:18:03 web.1  | --------------------------------------------------------------------------------
19:18:03 web.1  | DEBUG in controllers [/Users/chrwelsh/src/private/geemusic/geemusic/controllers.py:20]:
19:18:03 web.1  | URL is https://r1---sn-uxa3vh-j2ul.c.doc-0-0-sj.sj.googleusercontent.com/videoplayback?id=<bla></bla>mv=m&pl=17
19:18:03 web.1  | --------------------------------------------------------------------------------
19:18:13 web.1  | 127.0.0.1 - - [01/May/2017 19:18:13] "GET /alexa/stream/Tgarv4vwobsxyxtsott6p4qok5q HTTP/1.1" 200 -
19:18:31 web.1  | 127.0.0.1 - - [01/May/2017 19:18:31] "POST /alexa HTTP/1.1" 400 -
```

The r1 url works fine if I paste it into my browser.

There were no errors when I ran "pip3 install -r requirements.txt".

I've seen lots of issues here about ssl certificates, but was under the impression that ngrok was still supposed to work.

**Comment by apastel** [comment]
Same issue here. Using foreman and ngrok. Song is fetched and URL is correct, but no audio coming out of the echo.

**Comment by mycol** [comment]
I had weird issues until I deleted the skill and re-crearted, minding the SSL step as well and now it seems to work. The only issue I'm noticing now is the inability to play Tool songs (even thought I uploaded the albums to my play music account). I believe that is due to Tool not streaming to google music premium services (which I have a free trial of at the moment).

**Comment by apastel** [comment]
Just tried deleting and re-creating the skill....no such luck here. 

Yeah, I don't think the Gee Music app will stream anything that isn't part of Google's collection. Either that, or this is technology's way of protesting them taking too long to release a new album.

**Comment by mycol** [comment]
Bummer :(

The only difference I notice between your Foreman output and mine is the server address my foreman uses is 0.0.0.0 instead of 127.0.0.1. Not sure where that IP is pulled from by maybe it's a routing issue?

Lastly, I've had some fairly picky firewalls in the past, could anything be filtering that audio stream inbound to your network?

**Comment by llewmihs** [comment]
I was having a similar issue with my Pi3 setup. Alexa understood my request and thought it was playing, but i would get the following:
`POST /alexa                                    400 BAD REQUEST`                  
`GET  /alexa/stream/T2mg25e7ntiubsoslhg3nr63624 440 BAD REQUEST `

My solution to the problem was as follows:
In the .env file i had beed including `/alexa` at the end of the APPURL. This seemed like what I was supposed to do according to the README.
After reading a few issues, I noticed that someone had removed the `/alexa` in their setup. I did the same and all problems were solved.
To clarify - 
Alexa skill has /alexa on the end of the APP_URL, but the `.env.` file does not.
I hope this helps.
